server:
  port: 8000
  mode: development

database:
  host: postgres
  port: 5432
  user: elhadi
  password: test123
  name: compass
  sslmode: disable
  timezone: UTC
  max_open_conns: 25
  max_idle_conns: 25
  conn_max_lifetime: "1h"

redis:
  host: redis
  port: 6379
  password: ""
  db: 0

auth:
  jwt_secret: a82552a2c8133eddce94cc781f716cdcb911d065528783a8a75256aff6731886
  token_expiry_hours: 24
  issuer: compass-api

cors:
  allowed_origins:
    - "http://localhost:3000"
    - "http://localhost:8000"
  allowed_methods:
    - GET
    - POST
    - PUT
    - PATCH
    - DELETE
    - OPTIONS
  allowed_headers:
    - Origin
    - Content-Type
    - Accept
    - Authorization
    - X-Request-ID
    - X-Correlation-ID
  allow_credentials: true
  max_age: 12h

logging:
  level: debug
  format: json

swagger:
  enabled: true
  title: "Compass API"
  description: "API documentation for Compass application"
  version: "1.0.0"
  host: "localhost:8000"
  base_path: "/api" 