"""add_username_field_to_users

Revision ID: 04ed7f11165b
Revises: 467ad99fda4c
Create Date: 2024-12-01 17:22:18.682730

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04ed7f11165b'
down_revision: Union[str, None] = '467ad99fda4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add username column as nullable first
    op.add_column('users', sa.Column('username', sa.String(length=50), nullable=True))
    
    # Update existing records with username from email
    connection = op.get_bind()
    connection.execute(sa.text("""
        UPDATE users 
        SET username = SPLIT_PART(email, '@', 1) 
        WHERE username IS NULL
    """))
    
    # Make username non-nullable and add constraints
    op.alter_column('users', 'username', nullable=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_unique_constraint('uq_users_username', 'users', ['username'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_users_username', 'users', type_='unique')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_column('users', 'username')
    # ### end Alembic commands ###
