"""Add task history and comment relationships

Revision ID: 353b8fef4a73
Revises: 6427bb4caebd
Create Date: 2024-12-02 12:53:50.788362

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '353b8fef4a73'
down_revision: Union[str, None] = '6427bb4caebd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
