"""add resource and action to permissions

Revision ID: 62a1d1a625f4
Revises: de2e5e16d4c8
Create Date: 2024-12-01 11:08:08.517635

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62a1d1a625f4'
down_revision: Union[str, None] = 'de2e5e16d4c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('permissions', sa.Column('resource', sa.String(length=50), nullable=False))
    op.add_column('permissions', sa.Column('action', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('permissions', 'action')
    op.drop_column('permissions', 'resource')
    # ### end Alembic commands ###
