"""Update User-Role relationships

Revision ID: 6427bb4caebd
Revises: c33a7e74a227
Create Date: 2024-12-02 12:51:09.088782

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6427bb4caebd'
down_revision: Union[str, None] = 'c33a7e74a227'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
