"""Add user account locking fields

Revision ID: 7ae1c0975b85
Revises: 04ed7f11165b
Create Date: 2024-12-02 10:57:37.327388

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7ae1c0975b85'
down_revision: Union[str, None] = '04ed7f11165b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    pass


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
