"""Add user created_workflows relationship

Revision ID: e08fb51aedfb
Revises: 5f57db7e380f
Create Date: 2024-12-02 12:57:37.294546

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e08fb51aedfb'
down_revision: Union[str, None] = '5f57db7e380f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
