"""add_task_and_workflow_enhancements

Revision ID: f75f6fdb4c5d
Revises: add_name_fields
Create Date: 2024-12-01 07:25:20.463095

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f75f6fdb4c5d'
down_revision: Union[str, None] = 'add_name_fields'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
