"""add custom recurrence

Revision ID: 6fe6e0168311
Revises: 648aa1f1f228
Create Date: 2025-03-13 02:42:00.103052+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6fe6e0168311'
down_revision: Union[str, None] = '648aa1f1f228'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('recurrence_custom_days', postgresql.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'recurrence_custom_days')
    # ### end Alembic commands ###
