"""adding enum types of events

Revision ID: d29bc4f23ddc
Revises: 26e855a48579
Create Date: 2025-03-29 22:06:54.151005+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import enum

# Define the enum in Python first
class EventType(enum.Enum):
    NONE = "None"
    TASK = "Task"
    MEETING = "Meeting"
    TODO = "Todo"
    HOLIDAY = "Holiday"
    REMINDER = "Reminder"

# revision identifiers, used by Alembic.
revision: str = 'd29bc4f23ddc'
down_revision: Union[str, None] = '26e855a48579'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create the enum type first, before using it in tables
    eventtype = postgresql.ENUM('NONE', 'TASK', 'MEETING', 'TODO', 'HOLIDAY', 'REMINDER', name='eventtype')
    eventtype.create(op.get_bind())
    
    # Now add the column using the created enum type
    op.add_column('calendar_events', sa.Column('event_type', sa.Enum('NONE', 'TASK', 'MEETING', 'TODO', 'HOLIDAY', 'REMINDER', name='eventtype'), server_default='NONE', nullable=False))
    
    op.alter_column('calendar_events', 'status',
               existing_type=postgresql.ENUM('TODO', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', 'BLOCKED', 'UNDER_REVIEW', 'DEFERRED', name='taskstatus'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('calendar_events', 'duration',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.add_column('event_occurrences', sa.Column('event_type', sa.Enum('NONE', 'TASK', 'MEETING', 'TODO', 'HOLIDAY', 'REMINDER', name='eventtype'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event_occurrences', 'event_type')
    op.alter_column('calendar_events', 'duration',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('calendar_events', 'status',
               existing_type=postgresql.ENUM('TODO', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', 'BLOCKED', 'UNDER_REVIEW', 'DEFERRED', name='taskstatus'),
               server_default=sa.text("'TODO'::taskstatus"),
               existing_nullable=False)
    op.drop_column('calendar_events', 'event_type')
    
    # Drop the enum type
    eventtype = postgresql.ENUM('NONE', 'TASK', 'MEETING', 'TODO', 'HOLIDAY', 'REMINDER', name='eventtype')
    eventtype.drop(op.get_bind())
    # ### end Alembic commands ###
