"""modify indexes

Revision ID: 81634a92c4c5
Revises: a178888b2410
Create Date: 2025-02-14 17:27:56.997402+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81634a92c4c5'
down_revision: Union[str, None] = 'a178888b2410'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_sessions_token', table_name='sessions')
    op.create_index('ix_sessions_token', 'sessions', ['token'], unique=True)
    op.create_unique_constraint(None, 'sessions', ['token'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sessions', type_='unique')
    op.drop_index('ix_sessions_token', table_name='sessions')
    op.create_index('ix_sessions_token', 'sessions', ['token'], unique=False)
    # ### end Alembic commands ###
