"""Added UPCOMING to taskstatus

Revision ID: f0ce70671f28
Revises: d29bc4f23ddc
Create Date: 2025-03-30 04:11:42.338998+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f0ce70671f28'
down_revision: Union[str, None] = 'd29bc4f23ddc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('calendar_events', 'event_type',
               existing_type=postgresql.ENUM('NONE', 'TASK', 'MEETING', 'TODO', 'HOLIDAY', 'REMINDER', name='eventtype'),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('calendar_events', 'event_type',
               existing_type=postgresql.ENUM('NONE', 'TASK', 'MEETING', 'TODO', 'HOLIDAY', 'REMINDER', name='eventtype'),
               server_default=sa.text("'NONE'::eventtype"),
               existing_nullable=False)
    # ### end Alembic commands ###
