"""fix task models data

Revision ID: 52e9f72612fb
Revises: 5a9df8a8667b
Create Date: 2025-02-22 19:48:19.390586+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '52e9f72612fb'
down_revision: Union[str, None] = '5a9df8a8667b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('_dependencies_list', sa.JSON(), nullable=False))
    op.drop_column('tasks', 'dependencies')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('dependencies', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.drop_column('tasks', '_dependencies_list')
    # ### end Alembic commands ###
