"""fix

Revision ID: bc5452a3701c
Revises: 833720bf63d6
Create Date: 2025-03-07 05:17:42.007811+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc5452a3701c'
down_revision: Union[str, None] = '833720bf63d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workflow_agent_interactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workflow_id', sa.Integer(), nullable=True),
    sa.Column('agent_id', sa.Integer(), nullable=True),
    sa.Column('interaction_type', sa.String(length=100), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('input_data', sa.JSON(), nullable=True),
    sa.Column('output_data', sa.JSON(), nullable=True),
    sa.Column('execution_time', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('performance_metrics', sa.JSON(), nullable=True),
    sa.Column('optimization_suggestions', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agent_actions.id'], ),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_workflow_agent_interactions_agent_id', 'workflow_agent_interactions', ['agent_id'], unique=False)
    op.create_index('ix_workflow_agent_interactions_created_at', 'workflow_agent_interactions', ['created_at'], unique=False)
    op.create_index(op.f('ix_workflow_agent_interactions_id'), 'workflow_agent_interactions', ['id'], unique=False)
    op.create_index('ix_workflow_agent_interactions_status', 'workflow_agent_interactions', ['status'], unique=False)
    op.create_index('ix_workflow_agent_interactions_workflow_id', 'workflow_agent_interactions', ['workflow_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_workflow_agent_interactions_workflow_id', table_name='workflow_agent_interactions')
    op.drop_index('ix_workflow_agent_interactions_status', table_name='workflow_agent_interactions')
    op.drop_index(op.f('ix_workflow_agent_interactions_id'), table_name='workflow_agent_interactions')
    op.drop_index('ix_workflow_agent_interactions_created_at', table_name='workflow_agent_interactions')
    op.drop_index('ix_workflow_agent_interactions_agent_id', table_name='workflow_agent_interactions')
    op.drop_table('workflow_agent_interactions')
    # ### end Alembic commands ###
