"""fix data types

Revision ID: 579458d66d10
Revises: 78aa30ace51e
Create Date: 2025-02-14 21:17:20.781471+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '579458d66d10'
down_revision: Union[str, None] = '78aa30ace51e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflows', sa.Column('config', sa.JSON(), nullable=True))
    op.add_column('workflows', sa.Column('workflow_metadata', sa.JSON(), nullable=True))
    op.alter_column('workflows', 'status',
               existing_type=postgresql.ENUM('ACTIVE', 'ARCHIVED', name='workflowstatus'),
               type_=sa.String(length=50),
               nullable=True)
    op.drop_index('ix_workflow_created_at', table_name='workflows')
    op.drop_index('ix_workflow_created_by', table_name='workflows')
    op.drop_index('ix_workflow_organization_id', table_name='workflows')
    op.drop_index('ix_workflow_status', table_name='workflows')
    op.drop_index('ix_workflow_version', table_name='workflows')
    op.drop_index('ix_workflows_name', table_name='workflows')
    op.drop_constraint('workflows_organization_id_fkey', 'workflows', type_='foreignkey')
    op.drop_column('workflows', 'published_at')
    op.drop_column('workflows', 'settings')
    op.drop_column('workflows', 'archived_at')
    op.drop_column('workflows', 'version')
    op.drop_column('workflows', 'permissions')
    op.drop_column('workflows', 'organization_id')
    op.drop_column('workflows', 'triggers')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflows', sa.Column('triggers', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('workflows', sa.Column('organization_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('workflows', sa.Column('permissions', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('workflows', sa.Column('version', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('workflows', sa.Column('archived_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('workflows', sa.Column('settings', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('workflows', sa.Column('published_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.create_foreign_key('workflows_organization_id_fkey', 'workflows', 'organizations', ['organization_id'], ['id'])
    op.create_index('ix_workflows_name', 'workflows', ['name'], unique=False)
    op.create_index('ix_workflow_version', 'workflows', ['version'], unique=False)
    op.create_index('ix_workflow_status', 'workflows', ['status'], unique=False)
    op.create_index('ix_workflow_organization_id', 'workflows', ['organization_id'], unique=False)
    op.create_index('ix_workflow_created_by', 'workflows', ['created_by'], unique=False)
    op.create_index('ix_workflow_created_at', 'workflows', ['created_at'], unique=False)
    op.alter_column('workflows', 'status',
               existing_type=sa.String(length=50),
               type_=postgresql.ENUM('ACTIVE', 'ARCHIVED', name='workflowstatus'),
               nullable=False)
    op.drop_column('workflows', 'workflow_metadata')
    op.drop_column('workflows', 'config')
    # ### end Alembic commands ###
