"""update task model

Revision ID: 11da416196f7
Revises: 4b869ec53f95
Create Date: 2025-03-10 22:18:29.793993+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '11da416196f7'
down_revision: Union[str, None] = '4b869ec53f95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column(
        'start_date', sa.DateTime(), nullable=True))
    op.add_column('tasks', sa.Column('end_date', sa.DateTime(), nullable=True))
    op.execute("UPDATE tasks SET start_date = NOW() WHERE start_date IS NULL")
    op.alter_column('tasks', 'start_date', nullable=False)
    op.drop_index('ix_task_due_date', table_name='tasks')
    op.create_index('ix_task_end_date', 'tasks', ['end_date'], unique=False)
    op.create_index('ix_task_start_date', 'tasks', ['start_date'], unique=False)
    op.drop_column('tasks', 'due_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('due_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_index('ix_task_start_date', table_name='tasks')
    op.drop_index('ix_task_end_date', table_name='tasks')
    op.create_index('ix_task_due_date', 'tasks', ['due_date'], unique=False)
    op.drop_column('tasks', 'end_date')
    op.drop_column('tasks', 'start_date')
    # ### end Alembic commands ###
