"""fix issues

Revision ID: a178888b2410
Revises: 864496d259d9
Create Date: 2025-02-14 14:52:18.307182+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a178888b2410'
down_revision: Union[str, None] = '864496d259d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('token', sa.String(length=255), nullable=False))
    op.add_column('sessions', sa.Column('is_valid', sa.Boolean(), nullable=True))
    op.drop_index('ix_sessions_session_token', table_name='sessions')
    op.create_index('ix_sessions_token', 'sessions', ['token'], unique=False)
    op.drop_column('sessions', 'session_token')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('session_token', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_index('ix_sessions_token', table_name='sessions')
    op.create_index('ix_sessions_session_token', 'sessions', ['session_token'], unique=False)
    op.drop_column('sessions', 'is_valid')
    op.drop_column('sessions', 'token')
    # ### end Alembic commands ###
