"""change to enum

Revision ID: 36918183f5b6
Revises: dd4d22bd8457
Create Date: 2025-03-16 05:34:58.013833+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36918183f5b6'
down_revision: Union[str, None] = 'dd4d22bd8457'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "ALTER TABLE task_occurrences ALTER COLUMN status TYPE taskstatus USING status::taskstatus")
    op.execute(
        "ALTER TABLE task_occurrences ALTER COLUMN priority TYPE taskpriority USING priority::taskpriority")

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('task_occurrences', 'priority',
                    existing_type=sa.Enum(
                        'LOW', 'MEDIUM', 'HIGH', 'URGENT', name='taskpriority'),
                    type_=sa.VARCHAR(),
                    existing_nullable=True)
    op.alter_column('task_occurrences', 'status',
                    existing_type=sa.Enum('TODO', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED',
                                          'BLOCKED', 'UNDER_REVIEW', 'DEFERRED', name='taskstatus'),
                    type_=sa.VARCHAR(),
                    existing_nullable=True)
    # ### end Alembic commands ###
