"""add ai fields

Revision ID: 9f02b7826df3
Revises: 36918183f5b6
Create Date: 2025-03-21 07:09:26.983913+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f02b7826df3'
down_revision: Union[str, None] = '36918183f5b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_models', sa.Column('provider', sa.String(length=100), nullable=True))
    op.add_column('ai_models', sa.Column('api_key_reference', sa.String(length=255), nullable=True))
    op.add_column('ai_models', sa.Column('max_tokens', sa.Integer(), nullable=True))
    op.add_column('ai_models', sa.Column('temperature', sa.Float(), nullable=True))
    op.add_column('ai_models', sa.Column('last_used', sa.DateTime(), nullable=True))
    op.add_column('ai_models', sa.Column('total_requests', sa.Integer(), nullable=True))
    op.add_column('ai_models', sa.Column('average_latency', sa.Float(), nullable=True))
    op.add_column('ai_models', sa.Column('cost_per_request', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ai_models', 'cost_per_request')
    op.drop_column('ai_models', 'average_latency')
    op.drop_column('ai_models', 'total_requests')
    op.drop_column('ai_models', 'last_used')
    op.drop_column('ai_models', 'temperature')
    op.drop_column('ai_models', 'max_tokens')
    op.drop_column('ai_models', 'api_key_reference')
    op.drop_column('ai_models', 'provider')
    # ### end Alembic commands ###
