"""fix things

Revision ID: c6855ead97c2
Revises: 58a1ebb9214c
Create Date: 2025-02-14 17:32:48.593492+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6855ead97c2'
down_revision: Union[str, None] = '58a1ebb9214c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflows', sa.Column('organization_id', sa.Integer(), nullable=False))
    op.create_index('ix_workflow_organization_id', 'workflows', ['organization_id'], unique=False)
    op.create_foreign_key(None, 'workflows', 'organizations', ['organization_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'workflows', type_='foreignkey')
    op.drop_index('ix_workflow_organization_id', table_name='workflows')
    op.drop_column('workflows', 'organization_id')
    # ### end Alembic commands ###
