"""add and fix things

Revision ID: ac57474afd84
Revises: b44a481dd831
Create Date: 2025-02-22 05:31:56.510416+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ac57474afd84'
down_revision: Union[str, None] = 'b44a481dd831'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('_completion_date', sa.DateTime(), nullable=True))
    op.drop_column('todos', 'completion_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('completion_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('todos', '_completion_date')
    # ### end Alembic commands ###
