"""add more relations for the system

Revision ID: bad573cd2500
Revises: f9229d5717a7
Create Date: 2025-02-14 21:57:00.108430+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bad573cd2500'
down_revision: Union[str, None] = 'f9229d5717a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_file_created_at', 'files', ['created_at'], unique=False)
    op.create_index('ix_file_type', 'files', ['file_type'], unique=False)
    op.create_index('ix_file_user_id', 'files', ['user_id'], unique=False)
    op.create_index('ix_payments_payment_date', 'payments', ['payment_date'], unique=False)
    op.create_index('ix_payments_status', 'payments', ['status'], unique=False)
    op.create_index('ix_payments_subscription_id', 'payments', ['subscription_id'], unique=False)
    op.create_index('ix_payments_transaction_id', 'payments', ['transaction_id'], unique=True)
    op.create_index('ix_subscription_plans_created_at', 'subscription_plans', ['created_at'], unique=False)
    op.create_index('ix_subscription_plans_name', 'subscription_plans', ['name'], unique=True)
    op.create_index('ix_subscriptions_expires_at', 'subscriptions', ['expires_at'], unique=False)
    op.create_index('ix_subscriptions_plan_id', 'subscriptions', ['plan_id'], unique=False)
    op.create_index('ix_subscriptions_status', 'subscriptions', ['status'], unique=False)
    op.create_index('ix_subscriptions_user_id', 'subscriptions', ['user_id'], unique=False)
    op.create_index('ix_task_attachments_created_at', 'task_attachments', ['created_at'], unique=False)
    op.create_index('ix_task_attachments_file_type', 'task_attachments', ['file_type'], unique=False)
    op.create_index('ix_task_attachments_task_id', 'task_attachments', ['task_id'], unique=False)
    op.create_index('ix_task_attachments_uploaded_by', 'task_attachments', ['uploaded_by'], unique=False)
    op.add_column('users', sa.Column('phone_number', sa.String(length=20), nullable=True))
    op.create_index('ix_user_phone_number', 'users', ['phone_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_phone_number', table_name='users')
    op.drop_column('users', 'phone_number')
    op.drop_index('ix_task_attachments_uploaded_by', table_name='task_attachments')
    op.drop_index('ix_task_attachments_task_id', table_name='task_attachments')
    op.drop_index('ix_task_attachments_file_type', table_name='task_attachments')
    op.drop_index('ix_task_attachments_created_at', table_name='task_attachments')
    op.drop_index('ix_subscriptions_user_id', table_name='subscriptions')
    op.drop_index('ix_subscriptions_status', table_name='subscriptions')
    op.drop_index('ix_subscriptions_plan_id', table_name='subscriptions')
    op.drop_index('ix_subscriptions_expires_at', table_name='subscriptions')
    op.drop_index('ix_subscription_plans_name', table_name='subscription_plans')
    op.drop_index('ix_subscription_plans_created_at', table_name='subscription_plans')
    op.drop_index('ix_payments_transaction_id', table_name='payments')
    op.drop_index('ix_payments_subscription_id', table_name='payments')
    op.drop_index('ix_payments_status', table_name='payments')
    op.drop_index('ix_payments_payment_date', table_name='payments')
    op.drop_index('ix_file_user_id', table_name='files')
    op.drop_index('ix_file_type', table_name='files')
    op.drop_index('ix_file_created_at', table_name='files')
    # ### end Alembic commands ###
