"""Add streak_start_date column

Revision ID: 4b869ec53f95
Revises: b9d98867dff1
Create Date: 2025-03-10 03:34:15.507748+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b869ec53f95'
down_revision: Union[str, None] = 'b9d98867dff1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_habits', sa.Column('streak_start_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('daily_habits', 'streak_start_date')
    # ### end Alembic commands ###
