"""adding color's and location and other coloumns to the event and the occurrence

Revision ID: 11aa868694b3
Revises: f0ce70671f28
Create Date: 2025-03-30 19:25:57.392121+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11aa868694b3'
down_revision: Union[str, None] = 'f0ce70671f28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calendar_events', sa.Column('time_zone', sa.String(length=50), nullable=True))
    op.add_column('calendar_events', sa.Column('transparency', sa.String(length=50), nullable=True))
    op.add_column('calendar_events', sa.Column('color', sa.String(length=7), nullable=True))
    op.add_column('calendar_events', sa.Column('recurrence_count', sa.Integer(), nullable=True))
    op.add_column('event_occurrences', sa.Column('transparency', sa.String(length=50), nullable=True))
    op.add_column('event_occurrences', sa.Column('color', sa.String(length=7), nullable=True))
    op.add_column('event_occurrences', sa.Column('time_zone', sa.String(length=50), nullable=True))
    op.add_column('event_occurrences', sa.Column('location', sa.String(length=255), nullable=True))
    op.add_column('event_occurrences', sa.Column('is_all_day', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event_occurrences', 'is_all_day')
    op.drop_column('event_occurrences', 'location')
    op.drop_column('event_occurrences', 'time_zone')
    op.drop_column('event_occurrences', 'color')
    op.drop_column('event_occurrences', 'transparency')
    op.drop_column('calendar_events', 'recurrence_count')
    op.drop_column('calendar_events', 'color')
    op.drop_column('calendar_events', 'transparency')
    op.drop_column('calendar_events', 'time_zone')
    # ### end Alembic commands ###
