"""fix relations issues

Revision ID: 700ec7cc6159
Revises: 33440da881f1
Create Date: 2024-12-28 15:18:52.337067

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '700ec7cc6159'
down_revision: Union[str, None] = '33440da881f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(op.f('uq_organizations_user_id'), 'organizations', ['user_id'])
    op.create_foreign_key('fk_organization_user_id', 'organizations', 'users', ['user_id'], ['id'])
    op.add_column('permissions', sa.Column('role_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(op.f('uq_permissions_role_id'), 'permissions', ['role_id'])
    op.create_foreign_key('fk_premission_role_id', 'permissions', 'roles', ['role_id'], ['id'])
    op.create_unique_constraint('uq_role_permission', 'role_permissions', ['role_id', 'permission_id'])
    op.add_column('roles', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(op.f('uq_roles_user_id'), 'roles', ['user_id'])
    op.create_foreign_key('fk_role_user_id', 'roles', 'users', ['user_id'], ['id'])
    op.create_unique_constraint('uq_task_tags', 'task_tags', ['task_id', 'tag_id'])
    op.create_unique_constraint('uq_user_role', 'user_roles', ['user_id', 'role_id'])
    op.create_unique_constraint(op.f('uq_users_email'), 'users', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_users_email'), 'users', type_='unique')
    op.drop_constraint('uq_user_role', 'user_roles', type_='unique')
    op.drop_constraint('uq_task_tags', 'task_tags', type_='unique')
    op.drop_constraint('fk_role_user_id', 'roles', type_='foreignkey')
    op.drop_constraint(op.f('uq_roles_user_id'), 'roles', type_='unique')
    op.drop_column('roles', 'user_id')
    op.drop_constraint('uq_role_permission', 'role_permissions', type_='unique')
    op.drop_constraint('fk_premission_role_id', 'permissions', type_='foreignkey')
    op.drop_constraint(op.f('uq_permissions_role_id'), 'permissions', type_='unique')
    op.drop_column('permissions', 'role_id')
    op.drop_constraint('fk_organization_user_id', 'organizations', type_='foreignkey')
    op.drop_constraint(op.f('uq_organizations_user_id'), 'organizations', type_='unique')
    op.drop_column('organizations', 'user_id')
    # ### end Alembic commands ###
