"""fix

Revision ID: 81d0a7b4d7f1
Revises: 2f0b6d14c551
Create Date: 2025-02-14 06:11:47.399323

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '81d0a7b4d7f1'
down_revision: Union[str, None] = '2f0b6d14c551'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('token', sa.String(length=255), nullable=False))
    op.add_column('sessions', sa.Column('is_valid', sa.Boolean(), nullable=True))
    op.alter_column('sessions', 'expires_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('sessions', 'device_info',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('sessions', 'ip_address',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=45),
               existing_nullable=True)
    op.drop_constraint('sessions_session_token_key', 'sessions', type_='unique')
    op.create_index(op.f('ix_sessions_token'), 'sessions', ['token'], unique=True)
    op.drop_column('sessions', 'session_token')
    op.drop_column('sessions', 'user_agent')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('user_agent', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('sessions', sa.Column('session_token', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_sessions_token'), table_name='sessions')
    op.create_unique_constraint('sessions_session_token_key', 'sessions', ['session_token'])
    op.alter_column('sessions', 'ip_address',
               existing_type=sa.String(length=45),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('sessions', 'device_info',
               existing_type=sa.String(length=255),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('sessions', 'expires_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_column('sessions', 'is_valid')
    op.drop_column('sessions', 'token')
    # ### end Alembic commands ###
